import pandas as pd
import os
import ast
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib import colors
from reportlab.lib.units import inch
import sys

# Force UTF-8 for Windows Console
if sys.stdout.encoding.lower() != 'utf-8':
    sys.stdout.reconfigure(encoding='utf-8')
if sys.stderr.encoding.lower() != 'utf-8':
    sys.stderr.reconfigure(encoding='utf-8')

def generate_study_guide(
    notes_path="study_hub_output/notes.csv",
    flashcards_path="study_hub_output/flashcards.csv",
    quizzes_path="study_hub_output/quizzes.csv",
    output_path="study_hub_output/master_study_guide.pdf"
):
    print("📖 Building Master Study Guide PDF...")
    
    # Load data
    notes_df = pd.read_csv(notes_path) if os.path.exists(notes_path) else pd.DataFrame()
    fc_df = pd.read_csv(flashcards_path) if os.path.exists(flashcards_path) else pd.DataFrame()
    qz_df = pd.read_csv(quizzes_path) if os.path.exists(quizzes_path) else pd.DataFrame()

    # Document Setup
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        rightMargin=40, leftMargin=40,
        topMargin=40, bottomMargin=40
    )
    story = []
    
    # Styles
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle('TitleStyle', parent=styles['Heading1'], fontSize=32, alignment=1, spaceAfter=20, textColor=colors.HexColor("#1a472a"))
    subtitle_style = ParagraphStyle('SubTitle', parent=styles['Heading2'], fontSize=18, alignment=1, spaceAfter=40, textColor=colors.HexColor("#78716c"))
    subject_style = ParagraphStyle('SubjectStyle', parent=styles['Heading1'], fontSize=24, spaceAfter=15, textColor=colors.HexColor("#1e293b"))
    topic_style = ParagraphStyle('TopicStyle', parent=styles['Heading2'], fontSize=18, spaceAfter=10, textColor=colors.HexColor("#2563eb"))
    section_style = ParagraphStyle('SectionStyle', parent=styles['Heading3'], fontSize=14, spaceAfter=8, textColor=colors.HexColor("#065f46"))
    body_style = ParagraphStyle('BodyStyle', parent=styles['Normal'], fontSize=11, spaceAfter=10, leading=14)
    concept_style = ParagraphStyle('ConceptStyle', parent=styles['Normal'], fontSize=11, spaceAfter=6, leftIndent=20, leading=14)
    
    # Cover Page
    story.append(Spacer(1, 2 * inch))
    story.append(Paragraph("Master Study Guide", title_style))
    story.append(Paragraph("Generated by Python Automation System", subtitle_style))
    story.append(PageBreak())
    
    # Group by Subject
    if not notes_df.empty:
        subjects = notes_df['subject'].unique()
        
        for subject in subjects:
            story.append(Paragraph(f"Subject: {subject}", subject_style))
            story.append(Spacer(1, 10))
            
            subj_notes = notes_df[notes_df['subject'] == subject]
            topics = subj_notes['topic'].unique()
            
            for topic in topics:
                story.append(Paragraph(topic, topic_style))
                story.append(Spacer(1, 5))
                
                # 1. Notes
                topic_notes = subj_notes[subj_notes['topic'] == topic]
                for _, row in topic_notes.iterrows():
                    content_type = row['type']
                    content = str(row['content'])
                    
                    if content_type == 'summary':
                        story.append(Paragraph(f"<b>Summary:</b> {content}", body_style))
                        story.append(Spacer(1, 10))
                    elif content_type == 'section_title':
                        story.append(Paragraph(content, section_style))
                    elif content_type == 'section_body':
                        story.append(Paragraph(content, body_style))
                    elif content_type == 'concept':
                        story.append(Paragraph(f"• {content}", concept_style))
                
                story.append(Spacer(1, 15))
                
                # 2. Flashcards
                if not fc_df.empty:
                    topic_fc = fc_df[(fc_df['subject'] == subject) & (fc_df['topic'] == topic)]
                    if not topic_fc.empty:
                        story.append(Paragraph("Flashcards Review", section_style))
                        data = [["Question", "Answer"]]
                        for _, r in topic_fc.iterrows():
                            # Wrap text in Paragraphs for table cells
                            q_p = Paragraph(str(r['question']), body_style)
                            a_p = Paragraph(str(r['answer']), body_style)
                            data.append([q_p, a_p])
                        
                        table = Table(data, colWidths=[3.2*inch, 3.2*inch])
                        table.setStyle(TableStyle([
                            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#1a472a")),
                            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                            ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor("#f8fafc")),
                            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor("#e2ddd6")),
                            ('LEFTPADDING', (0, 0), (-1, -1), 8),
                            ('RIGHTPADDING', (0, 0), (-1, -1), 8),
                        ]))
                        story.append(table)
                        story.append(Spacer(1, 20))
                
                # 3. Practice Quiz
                if not qz_df.empty:
                    topic_qz = qz_df[(qz_df['subject'] == subject) & (qz_df['topic'] == topic)]
                    if not topic_qz.empty:
                        story.append(Paragraph("Practice Exam", section_style))
                        for idx, r in topic_qz.iterrows():
                            q_num = r['question_number']
                            q_text = str(r['question'])
                            story.append(Paragraph(f"<b>Q{q_num}:</b> {q_text}", body_style))
                            
                            try:
                                choices = ast.literal_eval(str(r['choices']))
                                letters = ['A', 'B', 'C', 'D']
                                for i, opt in enumerate(choices):
                                    story.append(Paragraph(f"   {letters[i]}) {opt}", concept_style))
                            except:
                                pass
                            
                            ans_val = r['correct_answer']
                            try:
                                ans_idx = int(ans_val)
                                ans_letter = ['A', 'B', 'C', 'D'][ans_idx] if ans_idx < 4 else str(ans_idx)
                                story.append(Paragraph(f"<i>Answer: {ans_letter}</i>", concept_style))
                            except ValueError:
                                story.append(Paragraph(f"<i>Answer: {ans_val}</i>", concept_style))
                            story.append(Spacer(1, 10))

                story.append(PageBreak())
                
    doc.build(story)
    print(f"✅ Successfully exported Master Study Guide to: {output_path}")

if __name__ == "__main__":
    generate_study_guide()
